export enum SocketEvent {
  UserVote = 'user_vote',
  UserAddRole = 'user_add_role',
  UserKick = 'user_kick',
  TaskCreate = 'task_create',
  TaskDelete = 'task_delete',
  TaskUpdateScore = 'task_set_score',
  TaskUpdateActive = 'task_set_active',
  TaskAvgScore = 'task_avg_score',
  RoomStart = 'room_start',
  RoomFinish = 'room_finish',
  RoomShow = 'room_show',
  RoomCreate = 'room_create',
  RoomJoin = 'room_join',
  RoomLeave = 'room_leave',
  RoomAdmin = 'room_admin',
  MessageCreate = 'message_create',
  ErrorNotData = 'error_not_data',
};
