export enum SocketEvent {
  UserVote = 'user_vote',
  TaskCreate = 'task_create',
  TaskDelete = 'task_delete',
  TaskUpdateScore = 'task_set_score',
  TaskUpdateActive = 'task_set_active',
  RoomStart = 'room_start',
  RoomFinish = 'room_finish',
  RoomRestart = 'room_restart',
  RoomCreate = 'room_create',
  RoomJoin = 'room_join',
  RoomLeave = 'room_leave',
  RoomAdmin = 'room_admin',
  MessageCreate = 'message_create',
  ErrorNotData = 'error_not_data',
};
